local palette = require 'themes.emzy.palette'
---@type table<string,vim.api.keyset.highlight|string>
return {
  Normal = { bg = palette.bg.dark, fg = palette.teal.light },
  NormalFloat = { bg = palette.bg.semidark, fg = palette.teal.light },
  NonText = { bg = palette.bg.dark, fg = palette.fg.dark },
  CursorLine = { bg = palette.bg.semidark },
  ColorColumn = { bg = palette.bg.mid },
  LineNr = { fg = palette.fg.dark },
  CursorLineNr = { fg = palette.bg.light },
  SignColumn = { bg = palette.bg.dark },
  StatusLine = { bold = true, bg = palette.purple.dark, fg = '#b78ce8' },
  StatusLineNC = { bold = true, bg = palette.purple.dark, fg = '#8151c0' },
  Directory = { fg = palette.blue.light },
  Visual = { bg = palette.teal.dark },
  Search = { bg = palette.teal.semidark, fg = palette.teal.light },
  CurSearch = { bg = palette.teal.mid, fg = palette.teal.light },
  IncSearch = { bg = palette.teal.mid, fg = palette.teal.light },
  MatchParen = { bg = palette.teal.semidark, fg = palette.teal.light },
  Pmenu = { bg = palette.bg.semidark, fg = palette.teal.light },
  PmenuBorder = { bg = palette.bg.semidark, fg = palette.purple.mid },
  PmenuThumb = { bg = palette.purple.mid },
  PmenuSel = { bg = palette.bg.light, fg = palette.teal.light },
  PmenuSbar = { bg = palette.teal.mid, fg = palette.teal.dark },
  VertSplit = { fg = palette.purple.dark },
  MoreMsg = { fg = palette.blue.light },
  Question = { fg = palette.blue.light },
  Title = { fg = palette.purple.light },

  ErrorMsg = { fg = palette.red.mid },
  Error = { fg = palette.red.mid },
  DiagnosticError = { fg = palette.red.mid },
  DiagnosticVirtualTextError = { bg = palette.neutral.mid, fg = palette.red.mid },
  WarningMsg = { fg = palette.yellow0 },
  DiagnosticWarn = { fg = palette.yellow0 },
  DiagnosticVirtualTextWarn = { bg = palette.neutral.mid, fg = palette.yellow0 },
  DiagnosticInfo = { fg = palette.teal.semidark },
  DiagnosticVirtualTextInfo = { bg = palette.neutral.mid, fg = palette.teal.semidark },
  DiagnosticHint = { fg = palette.teal.mid },
  DiagnosticVirtualTextHint = { bg = palette.neutral.mid, fg = palette.teal.mid },
  DiagnosticOk = { fg = palette.green.semilight },
}
